# 02. 파이썬 pandas 기초 연습문제

* 코난아카데미 : 데이터분석 기초
* 작성자 : 김무성    

# 차례

* 기초
* 응용

In [1]:
import pandas as pd
import numpy as np

## 기초 [1, 2, 3]

* numpy 기초
  - (numpy 기본) 문제 1. ndarray 다루기 (1)
  - (numpy 기본) 문제 2. ndarray 다루기 (2)
  - (numpy 선형대수) 문제 3. 선형방정식 풀기(해 구하기)
* pandas 기초
  - (pandas 기본) 문제 1. DataFrame 다루기 (1)
  - (pandas 기본) 문제 2. DataFrame 다루기 (2)

###  numpy 기초

#### (numpy 기본) 문제 1. ndarray 다루기 (1

##### 다음의 데이터를 사용하시오

In [2]:
ls = [2, 3, 5, 6, 7, 10]

##### a) 데이터 벡터 x를 만드시오

In [3]:
x = np.array(ls)
x

array([ 2,  3,  5,  6,  7, 10])

##### b) 각 데이터의 제곱으로 구성된 벡터 x2를 만드시오

In [4]:
x2 = x **2
x2

array([  4,   9,  25,  36,  49, 100])

##### c) 각 데이터의 제곱의 합을 구하시오

In [5]:
np.sum(x2)

223

##### d) 각 데이터에서 2를 뺀 값을 구하시오

In [6]:
x - 2

array([0, 1, 3, 4, 5, 8])

##### e) 최대값과 최소값을 구하시오

In [7]:
print(np.max(x) , np.min(x))

10 2


##### f) 5보다 큰 값들로만 구성된 데이터 벡터 x_up을 만드시오

In [8]:
print([i for i in x if i > 5])

[6, 7, 10]


##### g) 벡터 x의 길이를 구하시오

In [9]:
len(x)

6

##### h) x'x를 구하시오 (x'는 x의 전치)

In [10]:
np.dot(x.T,x)

223

##### i) xx'를 구하시오

In [11]:
np.dot(x,x.T)

223

##### j) 벡터 x와 x2를 열결합(column bind)하여 xc에 저장하시오

In [12]:
x

array([ 2,  3,  5,  6,  7, 10])

In [13]:
x2

array([  4,   9,  25,  36,  49, 100])

In [14]:
np.vstack((x,x2))

array([[  2,   3,   5,   6,   7,  10],
       [  4,   9,  25,  36,  49, 100]])

##### k) 벡터 x와 x2를 행결합(row bind)하여 xr에 저장하시오

In [15]:
np.hstack((x,x2))

array([  2,   3,   5,   6,   7,  10,   4,   9,  25,  36,  49, 100])

#### (numpy 기본) 문제 2. ndarray 다루기 (2)

##### a ) 표준정규분포를 따르는 난수 100개를 가진 배열 x를 만드시오

In [16]:
x = np.random.randn(100)

##### b) x에서 값이 0.2 보다 큰 원소들을 골라내시오

In [17]:
print([i for i in x if i > 0.2])

[0.5993727111980399, 0.29220809691254396, 0.4211139629792277, 0.9494446338462343, 0.4362034363200943, 1.3598171161942674, 0.6076024810056604, 0.7633093621245101, 2.390874746691497, 0.7539752674612259, 3.228086615592173, 0.7996425072414942, 0.41628170797137226, 0.3147416628497668, 2.3721703310805804, 0.7117665377560949, 1.458582371214783, 0.30083850325506595, 0.24781061789159056, 0.978067130196312, 0.8230107118313312, 1.1011265688865977, 1.660631438283861, 1.5198819123196863, 0.6080034484323176, 1.1235433547505247, 1.925709633211814, 2.1624432598333176, 0.3405214305128235, 1.2183978414143628, 0.2160555687681026, 0.7885100317936391, 0.9035264670395647, 1.581151524431132, 0.7545263143193979, 0.5648730350281637]


#### (numpy 선형대수) 문제 3. 선형방정식 풀기(해 구하기)

##### 다음과 같은 방정식이 있다.

3x + 6y - 5z = 12

x - 3y + 2z = -2

5x - y + 4z = 10

##### a) 위 식을 numpy를 이용해서 Ax=B 형태로 나타내시오 (A와 B만 생성)

In [18]:
A = np.array([[3,6,-5],[1,-3,2],[5,-1,4]])
A

array([[ 3,  6, -5],
       [ 1, -3,  2],
       [ 5, -1,  4]])

In [19]:
B = np.array([12,-2,10])

In [20]:
A.shape , B.shape

((3, 3), (3,))

##### b) A의 역행렬을 구하시오

In [21]:
np.linalg.inv(A)

array([[ 0.15625 ,  0.296875,  0.046875],
       [-0.09375 , -0.578125,  0.171875],
       [-0.21875 , -0.515625,  0.234375]])

##### c) 방정식의 해 벡터 x를 구하시오

In [22]:
np.dot(np.linalg.inv(A),B)

array([1.75, 1.75, 0.75])

### pandas 기초

#### (pandas 기본) 문제 1. DataFrame 다루기 (1)

   | numbers |
----- | ------ 
a  | 10 
b  | 20 
c  | 30 
d  | 40 


In [2]:
import pandas as pd

##### a) DataFrame으로 위와 같은 자료를 만드시오. 컬럼 이름은 numbers, 로우 네임은 a~e, 값은 10~40

In [10]:
df = pd.DataFrame([10,20,30,40],
                  index=['a','b','c','d'],
                  columns=['numbers'])
df

numbers
a       10
b       20
c       30
d       40

##### b) c 로우의 값을 가져오시오.

2가지 방법이 있음
loc과 iloc

둘의 차이점

loc은 index의 실제 값을 기준으로 추출함 일치하는걸로
iloc은 위치를 기반으로 뽑아옴, 몆번째 애냐

In [12]:
import numpy as np

In [13]:
df['square'] = np.square(df['numbers'])

In [15]:
df

numbers  square
a       10     100
b       20     400
c       30     900
d       40    1600

In [ ]:
데이터 프레임은 인덱스와 칼럼으로 구성되어 있잖아

In [ ]:
근데 얘를 칼럼 기준으로 뽑으면, series라고 부름

In [ ]:
series는 어떻게 생겼나면

In [22]:
df['numbers']

a    10
b    20
c    30
d    40
Name: numbers, dtype: int64

In [ ]:
얘는 column이 하나 밖에 없고, column의 이름이 없음
그냥 인덱스와 얘에 매칭되는 값만 존재, 마치 딕셔너리처럼
이걸 series라고 부름
이런 series의 결합이 dataframe

##### c) a, d 로우들의 값을 가져오시오.

In [41]:
df.loc[['a','d']]

numbers
a       10
d       40

##### d) numbers의 합을 구하시오.

In [18]:
df.sum()

numbers     100
square     3000
dtype: int64

In [ ]:
이렇게 치면 열을 기준으로 더함

만약 행을 기준으로 더하고 싶다면, axis라는 parameter를 인자로 넣어줄 수 있음

In [19]:
df.sum(axis = 1)

a     110
b     420
c     930
d    1640
dtype: int64

##### e) numbers의 값들을 각각 제곱하시오 (vectorized operations 표헌으로 예] 2*v )

###### 이런 결과가 나와야 함.

  | numbers |
----- | ------ 
a  | 100 
b  | 400 
c  | 900 
d  | 1600 

In [ ]:
apply는 데이터 프레임에 있는 모든 값에 접근해서, 얘들한테 어떤 연산을 수행하라는 함수임

In [ ]:
만약 정규화를 해야돼, 평균을 빼주고, 표준편차로 나눠줘야해,

In [ ]:
이럴 때 사용하면 유용함, 왜냐하면 모든 값에 일괄적으로 동일한 연산을 해주니까

In [ ]:
만약 5씩 빼고싶다면

In [21]:
df.apply(lambda x: x-5)

numbers  square
a        5      95
b       15     395
c       25     895
d       35    1595

In [ ]:
lambda는 배웠지? 축약형 함수라고 생각하면 됨
굿

In [20]:
df.apply(lambda x: x**2)

numbers   square
a      100    10000
b      400   160000
c      900   810000
d     1600  2560000

##### f) numbers의 값들을 각각 제곱하시오(apply 메서드 사용해서)

In [ ]:
만약 내가 여기다가 df.apply(lambda x: x**2) 라고 쓰면??

In [23]:
df.apply(lambda x: x**2)

numbers   square
a      100    10000
b      400   160000
c      900   810000
d     1600  2560000

In [ ]:
아까 만들어둔 square 까지 제곱되버림.. 나는 numbers만 제곱해야하는데
그래서 numbers만 추출해서 series를 뽑아내고, apply를 적용하면, numbers만 제곱시킬 수 있음


In [24]:
df['numbers'].apply(lambda x: x**2)

a     100
b     400
c     900
d    1600
Name: numbers, dtype: int64

In [ ]:
얘는 series를 뽑아내서 제곱시킨거라 값이 그대로 sereis형태지?

In [ ]:
하지만 동일한 방식으로 dataframe꼴로 뽑아낼 수 있음

In [ ]:
차이 비교

In [27]:
type(df['numbers'])

pandas.core.series.Series

In [28]:
type(df[['numbers']])

pandas.core.frame.DataFrame

In [ ]:
차이가 발생한 이유?

df[X] 형태인데
X가 str 타입이면 series로 뽑아냄
X가 list 형태이면 DataFrame으로 뽑아냄


In [30]:
X = 'numbers'

In [31]:
df[X] #series

a    10
b    20
c    30
d    40
Name: numbers, dtype: int64

In [32]:
X = ['numbers']

In [33]:
df[X] #dataFrame

numbers
a       10
b       20
c       30
d       40

In [ ]:
알아두면 유용

##### f) numbers의 값들을 각각 제곱하시오(apply 메서드에, 람다 함수도 사용해서)

In [45]:
df.apply(lambda x : x**2)

numbers
a      100
b      400
c      900
d     1600

##### g) floats라는 이름의 칼럼을 추가하시오. 값은 1.5, 2.5, 3.5, 4.5

###### 이런 결과가 나와야 함.

| numbers | floats
----- | ------ | ------
a  | 10 | 1.5
b  | 20 | 2.5
c  | 30 | 3.5
d  | 40 | 4.5

In [ ]:
칼럼을 추가하는 방법

In [34]:
df['내가 원하는 이름'] = [1,1,1,1]

In [35]:
df

numbers  square  내가 원하는 이름
a       10     100          1
b       20     400          1
c       30     900          1
d       40    1600          1

In [ ]:
하지만 길이가 안맞으면 에러


In [37]:
df['이름'] = [1,1,1,1]

In [39]:
df

numbers  square  내가 원하는 이름  이름
a       10     100          1   1
b       20     400          1   1
c       30     900          1   1
d       40    1600          1   1

In [46]:
df['floats'] = [i+0.5 for i in range(1,5)]
df

numbers  floats
a       10     1.5
b       20     2.5
c       30     3.5
d       40     4.5

##### h) names라는 이름의 다음과 같은 칼럼을 위의 결과에 또 추가하시오. 

 | names | 
 ----- | ------
 d  | Guido 
 a  | Felix
 b  | Francesc
 c  | Yves

In [47]:
testing_df = pd.DataFrame(['Guido','Felix','Francesc','Yves'],
                          index=['d','a','b','c'],
                          columns=['names'])

In [48]:
df

numbers  floats
a       10     1.5
b       20     2.5
c       30     3.5
d       40     4.5

In [49]:
testing_df

names
d     Guido
a     Felix
b  Francesc
c      Yves

In [50]:
df = pd.merge(df,testing_df, left_index=True, right_index=True)

In [51]:
df

numbers  floats     names
a       10     1.5     Felix
b       20     2.5  Francesc
c       30     3.5      Yves
d       40     4.5     Guido

##### i) 다음과 같은 정보를 가지는 로우(행)를 위의 결과에 추가하시오

index:z, 

numbers: 100, 

floats: 5.75, 

names: Henry

In [55]:
df.loc['z'] = [100, 5.75,'Henry']

In [56]:
df

numbers  floats     names
a       10    1.50     Felix
b       20    2.50  Francesc
c       30    3.50      Yves
d       40    4.50     Guido
z      100    5.75     Henry

##### j) squares 라는 이름의 칼럼을 위의 결과에 추가하시오. 그런데 squares는 인덱스값이 짝이 맞지 않으므로 join 메서드를 사용하시오(기본옵션으로)

  | squares |
----- | ------ 
a  | 1
b  | 4
c  | 9
d  | 16
y  | 25

In [57]:
testing_df = pd.DataFrame(data=[i**2 for i in range(1,6)],
                          columns=['squares'],
                          index=['a','b','c','d','y'])

In [58]:
testing_df

squares
a        1
b        4
c        9
d       16
y       25

In [59]:
df

numbers  floats     names
a       10    1.50     Felix
b       20    2.50  Francesc
c       30    3.50      Yves
d       40    4.50     Guido
z      100    5.75     Henry

In [60]:
pd.merge(df,testing_df, 
         how='inner',
         left_index=True, 
         right_index=True)

numbers  floats     names  squares
a       10     1.5     Felix        1
b       20     2.5  Francesc        4
c       30     3.5      Yves        9
d       40     4.5     Guido       16

##### k) j와 동일하나 join 메서드의 옵션을 'outer'로 바꿔서 수행해보시오.

In [63]:
pd.merge(df,testing_df, 
         how='outer',
         left_index=True, 
         right_index=True)

numbers  floats     names  squares
a     10.0    1.50     Felix      1.0
b     20.0    2.50  Francesc      4.0
c     30.0    3.50      Yves      9.0
d     40.0    4.50     Guido     16.0
y      NaN     NaN       NaN     25.0
z    100.0    5.75     Henry      NaN

In [62]:
new_df = pd.merge(df,testing_df, how='outer',left_index=True, right_index=True)
new_df

numbers  floats     names  squares
a     10.0    1.50     Felix      1.0
b     20.0    2.50  Francesc      4.0
c     30.0    3.50      Yves      9.0
d     40.0    4.50     Guido     16.0
y      NaN     NaN       NaN     25.0
z    100.0    5.75     Henry      NaN

##### l) 위의 결과로 나온 자료에서 numbers 칼럼과 squares 칼럼에 대해, 각각 평균을 구하시오. 다음과 같은 결과가 나와야 함. (mean 메서드 사용, column-wise 계산)

In [ ]:
numbers 40
squares 11

In [66]:
new_df['numbers'].mean()

40.0

In [67]:
new_df['squares'].mean()

11.0

##### m) numbers와 squares 칼럼에 대해, 각각 표준편차를 구하시오 (std 메서드 사용, column-wise 계산)

In [68]:
print(new_df['numbers'].std() , new_df['squares'].std())

35.35533905932738 9.669539802906858


#### (pandas 기본) 문제 2. DataFrame 다루기 (2)

##### a) 표준정규분포를 따르는 9 X 4 형태의 DataFrame을 생성하시오

In [69]:
rand_df = pd.DataFrame(np.random.randn(36).reshape(9,4))
rand_df

0         1         2         3
0 -0.350668 -0.722271  0.012790 -0.792629
1  0.366956 -0.573115 -0.242530 -1.505367
2  1.284112 -1.431092  0.676385  2.255145
3 -0.207949 -0.656263 -1.208690  0.137673
4  1.139832 -1.036374 -1.616088 -0.430377
5 -0.745572  0.007835 -1.234691 -0.949065
6  1.455116 -0.910608  1.064471  0.307524
7  1.715213 -0.333907 -1.038324  0.810768
8  1.069265  0.526334  0.060627  0.074937

##### b) a에서 생성한 DataFrame의 칼럼 이름을 - No1, No2, No2, No4로 지정하시오

In [70]:
rand_df.columns = ['No1','No2','No3','No4']
rand_df

No1       No2       No3       No4
0 -0.350668 -0.722271  0.012790 -0.792629
1  0.366956 -0.573115 -0.242530 -1.505367
2  1.284112 -1.431092  0.676385  2.255145
3 -0.207949 -0.656263 -1.208690  0.137673
4  1.139832 -1.036374 -1.616088 -0.430377
5 -0.745572  0.007835 -1.234691 -0.949065
6  1.455116 -0.910608  1.064471  0.307524
7  1.715213 -0.333907 -1.038324  0.810768
8  1.069265  0.526334  0.060627  0.074937

##### e) 위에서 생성된 자료에, 시간 관련 인덱싱을 하기 위해서는 DataTime 자료형을 생성해서 로우 인덱스에 넣어주는 방법이 있다.  아래코드를 실행하시오

In [71]:
# import pandas as pd 라는 가정하에.
dates = pd.date_range('2015-1-1', periods=9, freq='M')
rand_df.index = dates # a와 b를 거쳐서 만들어진 DataFrame 인스턴스의 변수명이 df라고 가정.
rand_df

No1       No2       No3       No4
2015-01-31 -0.350668 -0.722271  0.012790 -0.792629
2015-02-28  0.366956 -0.573115 -0.242530 -1.505367
2015-03-31  1.284112 -1.431092  0.676385  2.255145
2015-04-30 -0.207949 -0.656263 -1.208690  0.137673
2015-05-31  1.139832 -1.036374 -1.616088 -0.430377
2015-06-30 -0.745572  0.007835 -1.234691 -0.949065
2015-07-31  1.455116 -0.910608  1.064471  0.307524
2015-08-31  1.715213 -0.333907 -1.038324  0.810768
2015-09-30  1.069265  0.526334  0.060627  0.074937

##### f) 각 컬럼의 평균을 구하시오

In [72]:
rand_df.describe().loc['mean',:]

No1    0.636256
No2   -0.569940
No3   -0.391783
No4   -0.010154
Name: mean, dtype: float64

##### f) 5월부터 7월까지의, 각 컬럼의 평균을 구하시오

In [75]:
rand_df.iloc[[idx for idx, i in enumerate(rand_df.index) if 4 < i.month < 8]].mean()

No1    0.616458
No2   -0.646382
No3   -0.595436
No4   -0.357306
dtype: float64

## 응용

* 응용문제 1 - pandas의 DataFrame을 이용한 엑셀파일 분석
* 응용문제 2 - pandas의 DataFrame을 이용한 주식 데이터 분석 [3]

### 응용문제 1 - pandas의 DataFrame을 이용한 엑셀파일 분석

* 01_data/ex/person.xls 파일을 pandas로 읽어서 DataFrame 자료로 받는다.
* (힌트, 엑셀에서 열어서 csv 포맷으로 바꾸면 훨씬 쉬워진다)

##### 1) score의 평균을 구하기

In [80]:
person_df = pd.read_csv('person.csv',encoding='utf-8')
person_df

no  id  gender  email     com  score
0   1  ma    male    NaN   naver    100
1   2  fa  female    NaN  google    100
2   3  mb    male    NaN   yahoo     80
3   4  mc    male    NaN    daum     70
4   5  fb  female    NaN    daum     60
5   6  fc  female    NaN   naver     70
6   7  me    male    NaN   yahoo     80
7   8  md    male    NaN   naver    100
8   9  mg    male    NaN   naver     90
9  10  fd  female    NaN   naver     90

##### 2) 남,녀별 score 평균 구하기

In [81]:
person_df.groupby('gender').aggregate({'score':'mean'})

score
gender           
female  80.000000
male    86.666667

##### 3) 각 email의 값은 비워져있다. 채워넣어보자. 이메일은 '아이디@회사이름.com' 규칙을 따른다. 예를들어 id가 user1이고 회사가 naver이면 그 사람의 email은 user1@naver.com 이다.

In [82]:
person_df['email'] = [person_df['id'][i] +'@'+ person_df['com'][i] +'.com'for i in range(len(person_df))]
person_df

no  id  gender          email     com  score
0   1  ma    male   ma@naver.com   naver    100
1   2  fa  female  fa@google.com  google    100
2   3  mb    male   mb@yahoo.com   yahoo     80
3   4  mc    male    mc@daum.com    daum     70
4   5  fb  female    fb@daum.com    daum     60
5   6  fc  female   fc@naver.com   naver     70
6   7  me    male   me@yahoo.com   yahoo     80
7   8  md    male   md@naver.com   naver    100
8   9  mg    male   mg@naver.com   naver     90
9  10  fd  female   fd@naver.com   naver     90

### 응용문제 2 - pandas의 DataFrame을 이용한 주식 데이터 분석

##### 야후 파이낸스 API를 이용해서 특정 주식의 정보를 받아오는 코드는 아래와 같다. 

In [40]:
import pandas as pd
import pandas_datareader.data as web

start_date = '2010-01-01'
end_date = '2016-12-31'
panel_data = web.DataReader('INPX', 'yahoo', start_date, end_date)
# DAX = web.DataReader(name='APPL', data_source='yahoo', start='2000-1-1')
# DAX.info()

##### a) 위의 코드를 실행해서 값을 가져오시오

In [41]:
panel_data.head()

High      Low     Open    Close  Volume  Adj Close
Date                                                             
2012-08-03  15120.0  15120.0  15120.0  15120.0     0.0    15120.0
2012-08-06  15120.0  15120.0  15120.0  15120.0     0.0    15120.0
2012-08-07   5400.0   5400.0   5400.0   5400.0     0.0     5400.0
2012-08-08   5400.0   5400.0   5400.0   5400.0     0.0     5400.0
2012-08-09  16200.0  16200.0  16200.0  16200.0     0.0    16200.0

In [42]:
panel_data.index

DatetimeIndex(['2012-08-03', '2012-08-06', '2012-08-07', '2012-08-08',
               '2012-08-09', '2012-08-10', '2012-08-13', '2012-08-14',
               '2012-08-15', '2012-08-16',
               ...
               '2016-12-16', '2016-12-19', '2016-12-20', '2016-12-21',
               '2016-12-22', '2016-12-23', '2016-12-27', '2016-12-28',
               '2016-12-29', '2016-12-30'],
              dtype='datetime64[ns]', name='Date', length=1110, freq=None)

In [ ]:
시가 고가 저가 종가에서 고가-종가가 그날 최대 변동 폭이잖아

In [ ]:
그럼 이걸 어떻게 계산하나면
t일의 고가에서 t일의 저가를 빼야하잖아

그럼 t일의 고가를 뽑음

In [44]:
high = panel_data['High']

In [46]:
low = panel_data['Low']

In [ ]:
이게 그냥 빼버리면 알아서 같은 인덱스끼리 연산을 해줌

In [49]:
high.head()

Date
2012-08-03    15120.0
2012-08-06    15120.0
2012-08-07     5400.0
2012-08-08     5400.0
2012-08-09    16200.0
Name: High, dtype: float64

In [50]:
low.head()

Date
2012-08-03    15120.0
2012-08-06    15120.0
2012-08-07     5400.0
2012-08-08     5400.0
2012-08-09    16200.0
Name: Low, dtype: float64

In [ ]:
이게 series지만 개별 index는 t일이라는 정보를 가지고 있잖아

In [ ]:
index가 같은 애들끼리만 연산을 해줘서 그냥 빼버리면 알아서 일별 자료끼리 비교가 됨

##### b) High와 Low의 차이를 계산해서 Diff라는 이름의 칼럼을 만들어 그 결과를 반영하시오.

In [ ]:
얘를 새로운 칼럼 Diff라고 만들어줘야함 그럼 아까처럼 df['내가원하는이름'] = 내가 원하는 값

In [53]:
panel_data['Diff'] = panel_data['High'] - panel_data['Low']

In [54]:
panel_data.head()

High      Low     Open    Close  Volume  Adj Close  Diff
Date                                                                   
2012-08-03  15120.0  15120.0  15120.0  15120.0     0.0    15120.0   0.0
2012-08-06  15120.0  15120.0  15120.0  15120.0     0.0    15120.0   0.0
2012-08-07   5400.0   5400.0   5400.0   5400.0     0.0     5400.0   0.0
2012-08-08   5400.0   5400.0   5400.0   5400.0     0.0     5400.0   0.0
2012-08-09  16200.0  16200.0  16200.0  16200.0     0.0    16200.0   0.0

##### c) 2015년의 Open, High, Low, Close의 각 평균을 구하시오

In [ ]:
이게 내가 말한 조건으로 sorting하는 방법, 좀 복잡해보이지 하지만 어렵지 않음
리스트 컴프리헨션 배웠어?

In [55]:
[x for x in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
이거 알지

In [ ]:
여기서 맨 앞에 x가 람다함수 꼴이랑 똑같잖아

In [ ]:
lambda x: x

In [ ]:
만약 내가 0~9에서 숫자를 제곱해서 보고싶어

In [56]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
람다함수 꼴이기 때문에

In [ ]:
x에 어떤 연산을 해라 하면 

In [ ]:
[연산 for 개별 값 in iterable(리스트 같은걸 이터러블이라고 부름 복수개의 자료가 들어가있는 자료구조형, 리스트, 튜플, 등등..)

In [ ]:
리스트 컴프리헨션 문법은, iterable에서 값들을 하나씩 뽑아서 어떤 연산을 수행해라! 라는 형식임

In [ ]:
다시 보면
iterable은 range(10)이지? 이건 0~9까지 숫자의 집합이잖아
for x, 이건 여기서 하나씩 뽑은 애들을 x라고 부르겠다 라는 의미야
x**2 x라고 부르기로 했으니까 얘를 제곱해라

In [57]:
[x**2 for x in [1,2,3,4,5]]

[1, 4, 9, 16, 25]

In [ ]:
1,2,3,4,5에서 먼저 1을 뽑지, 얘를 x라고 부르고 , 제곱하지,
다음 2를 뽑지, 제곱하지 
굿?

In [ ]:
labmda x: 이거랑 똑같아 변수를 x라고 칭한다!

In [ ]:
여기에 근데 조건 식을 추가할 수 있음

만약 x가 OO이라면 XX하고, 아니면 CC해라

얘를 들어, 0~9의 숫자 중에 홀수이면 출력하고, 짝수이면 하지 마라,

In [58]:
[x for x in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
이러면 다 돌잖아

일단 다 돌고, 조건에 안맞으면 버리고, 조건에 맞으면 살리자

[x for x in range(10) if x%2 == 1]

SyntaxError: invalid syntax (<ipython-input-59-5e70b3051e1e>, line 1)

In [60]:
[x for x in range(10) if x%2 == 1]

[1, 3, 5, 7, 9]

In [ ]:
여기서 조건 식에 안맞으면 그냥 무시하고 건너뛰기 때문에 사실 2,4,6도 돌긴 도는데 그냥 무시한거
연산을 하지 않는거지
여기서 연산은 x를 그대로 출력하는게 연산

In [ ]:
그치?

In [ ]:
x%2 는 x를 2로 나눈 나머지 가 1이면 얜 홀수

In [ ]:
다시 여기로 돌아옴
2015년 주가의 평균을 구하고 싶어 종가 close

In [ ]:
그럼 일단 종가를뽑아보자

In [ ]:
아.. 이러면 2018년 자료부터 모두 다 뽑힘.. 근데 2015년 자료부터 뽑아야하는데..
data.loc을 활용하면 내가 원하는 인덱스를 뽑을 수 있겠지?


In [ ]:
아.. 에러남
왜냐..? 2015라는 이름과 매치되는 애들이 전혀 없기 때문

In [ ]:
일단 이 인덱스는 str타입이 아님, int타입도 아니고

In [66]:
type(panel_data.index[0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
timestamp라는 데이터 타입인데 얘 배움?
얘는 시간 연산을 쉽게 하기 위한 데이터임
근데 이걸 안써도 사실 할 수 있음
만약 이걸 str으로 바꾸면?

In [67]:
str(panel_data.index[0]) 굿 스트링 타입이 됬음 우리는 index가 2015인 애들만 뽑아야돼
그럼 str짜르는 법 배움?

'2012-08-03 00:00:00'

In [69]:
a = '안녕하세요'

In [71]:
a[:4]

'안녕하세'

In [72]:
date = str(panel_data.index[0])

In [73]:
date

'2012-08-03 00:00:00'

In [ ]:
얘를 앞에서 부터 4개 짤라서 보면 년도만 추출 가능 아님?

In [74]:
date[:4]

'2012'

In [ ]:
이제 얘가 2015랑 똑같은지만 보면 되는거 아님?

In [75]:
'2012' == '2015'

False

In [ ]:
그럼 전체 인덱스를 모두 돌면서, 얘를 스트링으로 바꾸고, 이걸 앞에서 4개만 짤라서 2015랑 똑같으면 뽑아라 라고 명령을 내리면 됨

In [ ]:
1번 iterable은 전체 인덱스
얘를 date라고 부르자
date를 str으로 바꾸고, 4개를 짤라서, 이게 만약 2015랑 같으면 얘를 포함시켜라

In [ ]:
my_index_list = [date for date in panel_data.index]

In [ ]:
이렇게 쓰면, 전체 데이터를 다 돌면서 다 원상태로 포함시켜라 잖아?

In [ ]:
하지만 우리는 조건 식이 필요함

In [76]:
my_index_list = [date for date in panel_data.index if str(date)[:4] == '2015']

In [ ]:
panel_data.loc[x하면 하나만 뽑잖아 한 줄만, 근데 여기에 list를 넣어주면 list에 있는 원소 개수만큼 뽑아옴]

In [80]:
panel_data.loc[my_index_list][['Close']].mean()

Close    25974.714286
dtype: float64

In [ ]:
2015년 종가의 평균 계산 끝

In [ ]:
논리만 있으면 다 짤수 있음

In [ ]:
내가 2015년이라는 걸 어떻게 추출할까? 라는걸 고민하면서 

In [ ]:
근데 이건, 해야 늘음, 무조건 많이 해야 늘음
형이 이런걸 보면서 음.. 나는 2015년 최고가를 구해보고 싶은데 아.. 어떻게하지


In [ ]:
일단 2015년 주가를 다 뽑아보자

In [ ]:
나중에는 그냥 한번에 바로 쳐짐

In [ ]:
지금 이만큼은 길어서 복잡해보이지만 사실 그냥 dataframe임,
이런 조건을 만족하는 dataFrame이야!

그래서 이 뒤에 dataframe에 대한 함수, 매서드를 적용하면 다 됨


In [ ]:
얘를 들어 데이터 프레임에서 한 열을 선택하고 싶어
그럼 dataframe['내가 원하는 열'] 이렇게 하면 되잖아

In [ ]:
이게 그거야

In [ ]:
dataframe.max()라는 함수가 있음 이건 칼럼별로, 제일 큰 값을 가져와라 인데
난 ㅏ이미 칼럼을 하나만 뽑아서 값이 하나만 나온거

In [ ]:
하지만 그냥 바로 떄리면, 전체 열을 기준으로 연산을 수행함

보통 연산은 열 기준으로 수행함

High의 2015년 최고가
Low는 2015년 최저가
등등

In [ ]:
max도 있으면 min도 있음

In [ ]:
일단 내가 OO조건을 만족하는 데이터에 XX연산을 하고 싶어..

라고 하면

OO 조건을 만족하는 데이터를 뽑아내고

XX 연산을 하는게 전체 과정임

XX연산은 이미 구현된 함수 일수도, 내가 직접 구현해야 할 수도,
하지만 OO조건을 만족하는 데이터를 뽑아내는게 정말 중요함

사실 복잡해보이는 내 코드도 다 그런 과정임



In [91]:
panel_data.loc[[date for date in panel_data.index if str(date)[:4] == '2015']].min()

High         10458.0
Low           9720.0
Open         10080.0
Close         9918.0
Volume           0.0
Adj Close     9918.0
Diff           180.0
dtype: float64

In [ ]:
근데 여기서 내가 생각하는 기능 있잖아? 제일 큰 값만 뽑아주는거 이런건 이미 모두 다 구횬되있음

내가 모르는 것 뿐이지..

In [61]:
panel_data['Close']

Date
2012-08-03    15120.0
2012-08-06    15120.0
2012-08-07     5400.0
2012-08-08     5400.0
2012-08-09    16200.0
2012-08-10    16200.0
2012-08-13    16200.0
2012-08-14     5400.0
2012-08-15     5400.0
2012-08-16    18360.0
2012-08-17    18360.0
2012-08-20    18360.0
2012-08-21    18360.0
2012-08-22    18360.0
2012-08-23    18360.0
2012-08-24    18360.0
2012-08-27    18360.0
2012-08-28    18360.0
2012-08-29    18360.0
2012-08-30    18360.0
2012-08-31    18360.0
2012-09-04    18360.0
2012-09-05    18360.0
2012-09-06    18360.0
2012-09-07    18360.0
2012-09-10    18360.0
2012-09-11    18360.0
2012-09-12    18360.0
2012-09-13    18360.0
2012-09-14    18360.0
               ...   
2016-11-17     3240.0
2016-11-18     3258.0
2016-11-21     3510.0
2016-11-22     3330.0
2016-11-23     3420.0
2016-11-25     3240.0
2016-11-28     5580.0
2016-11-29     5436.0
2016-11-30     4500.0
2016-12-01     4518.0
2016-12-02     5202.0
2016-12-05     4680.0
2016-12-06     3960.0
2016-12-07     3780.0
2016-

In [96]:
panel_data.loc[[idx for idx in panel_data.index if idx.year == 2015]].mean()

High         27474.642857
Low          24882.928571
Open         26326.571429
Close        25974.714286
Volume           7.142857
Adj Close    25974.714286
Diff          2591.714286
dtype: float64

## 참고자료 

 * [1] 데이터/수치 분석을 위한 파이썬 라이브러리 SciPy와 NumPy - http://www.hanbit.co.kr/ebook/look.html?isbn=9788968486135
 * [2] 파이썬 라이브러리를 활용한 데이터 분석 - http://www.hanbit.co.kr/book/look.html?isbn=978-89-6848-047-8
 * [3] Python for Finance - http://shop.oreilly.com/product/0636920032441.do